version: "3.6"

services:
  # Backend API
  smart-brain-api:
    container_name: backend
    # image: node:8.11.1
    build: ./
    command: npm start
    working_dir: /usr/src/smart-brain-api
    environment:
      POSTGRES_URI: postgres://admin:password@postgres:5432/smart-brain-docker
      REDIS_URI: redis://redis:6379
    links:
      - postgres
      - redis
    # Map port 3000 of the docker to host port
    ports:
      - "3000:3000"
    # Link the current directory to the one in the docker dir
    volumes:
      - ./:/usr/src/smart-brain-api
  # Postgres
  postgres:
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: smart-brain-docker
      POSTGRES_HOST: postgres
    build: ./postgres
    ports:
      - "5432:5432"
  # Redis
  # To access: docker-compose exec redis redis-cli
  redis:
    image: redis
    ports:
      - "6379:6379"
